version: '3'
services:
 bot:
  build: .
  depends_on:
    - "mongo"
  restart: always
  ports:
    - '9229:9229'
 mongo:
  image: "mongo"
  volumes:
    - ./mongo-volume:/data/db
  ports:
    - '27017:27017'